// SPDX-License-Identifier: GPL-3.0-only
// Metroidvania dashboard. Data comes from data.js (window.METROIDVANIA_DASHBOARD),
// generated by scripts/dashboard.py, so the page works from file:// without any request.
(function () {
  "use strict";

  const data = window.METROIDVANIA_DASHBOARD;
  const view = document.getElementById("view");
  const toolbar = document.getElementById("toolbar");
  const search = document.getElementById("search");
  const statusFilter = document.getElementById("status-filter");

  const VERDICTS = {
    passing: ["Tests passed", "ok"],
    failing: ["Tests failed", "bad"],
    tests_not_run: ["Tests not run", "warn"],
    untested: ["No tests", "warn"],
    unregistered_tests: ["Tests not registered", "warn"],
    missing_sources: ["Sources missing", "bad"],
  };
  const AREA_VIEWS = ["mzm", "aos", "metroidvania", "story", "tools", "assets", "platform"];
  const state = { view: "overview", query: "", statuses: new Set() };

  function esc(value) {
    return String(value == null ? "" : value).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    })[c]);
  }
  function statusInfo(id) {
    return data.statuses.find((s) => s.id === id) || { id, label: id, description: "" };
  }
  function statusBadge(id) {
    const s = statusInfo(id);
    return `<span class="badge" title="${esc(s.description)}"><span class="dot" style="background:var(--s-${esc(id)})"></span>${esc(s.label)}</span>`;
  }
  function verdictBadge(verification) {
    const [label, tone] = VERDICTS[verification.verdict] || [verification.verdict, "warn"];
    return `<span class="badge ${tone}" title="Checked automatically when the data was generated">${esc(label)}</span>`;
  }
  function percent(value) {
    return value == null ? "n/a" : `${value}%`;
  }
  function areaTitle(id) {
    const area = data.areas.find((a) => a.id === id);
    return area ? area.title : id;
  }

  function matches(feature) {
    if (state.statuses.size && !state.statuses.has(feature.status)) return false;
    if (!state.query) return true;
    const haystack = [feature.id, feature.title, feature.category, feature.limitations,
      feature.next_action, ...feature.local_sources, ...feature.tests,
      ...feature.native_routines].join(" ").toLowerCase();
    return state.query.split(/\s+/).every((word) => haystack.includes(word));
  }

  function stackBar(byStatus, total) {
    if (!total) return '<div class="stack"></div>';
    const parts = data.statuses.filter((s) => byStatus[s.id]).map((s) =>
      `<span style="width:${(100 * byStatus[s.id]) / total}%;background:var(--s-${s.id})" title="${esc(s.label)}: ${byStatus[s.id]}"></span>`);
    return `<div class="stack" role="img" aria-label="Status distribution">${parts.join("")}</div>`;
  }
  function legend(byStatus) {
    return `<div class="legend">${data.statuses.filter((s) => byStatus[s.id]).map((s) =>
      `<span><i style="background:var(--s-${s.id})"></i>${esc(s.label)} ${byStatus[s.id]}</span>`).join("")}</div>`;
  }
  function metric(label, value, count, total, cls) {
    return `<div class="metric"><div class="label"><span>${esc(label)}</span><span>${percent(value)} · ${count}/${total}</span></div>
      <div class="bar"><span class="${cls}" style="width:${value || 0}%"></span></div></div>`;
  }

  function featureCard(feature) {
    const v = feature.verification;
    const rows = [];
    const list = (items, mono) => items.map((x) => mono ? `<code>${esc(x)}</code>` : esc(x)).join(", ");
    if (feature.local_sources.length) rows.push(["Implementation", list(feature.local_sources, true)]);
    if (feature.tests.length) rows.push(["Tests", v.tests.map((t) =>
      `<code>${esc(t.test)}</code>${t.ctest && t.ctest.length ? ` <span class="muted">(${esc(t.ctest.join(", "))})</span>` : ""}${t.outcome ? ` — ${esc(t.outcome)}` : ""}`).join("<br>")]);
    if (feature.native_routines.length) rows.push(["Native routines", list(feature.native_routines, true)]);
    if (feature.dependencies.length) rows.push(["Depends on", list(feature.dependencies, true)]);
    rows.push(["Fidelity", esc(feature.fidelity)]);
    if (feature.limitations) rows.push(["Limitations", esc(feature.limitations)]);
    if (feature.next_action) rows.push(["Next", esc(feature.next_action)]);
    rows.push(["Declared in", `<code>${esc(feature.source)}</code>`]);
    if (v.verified_on) rows.push(["Verified", esc(v.verified_on)]);
    else if (feature.last_validated) rows.push(["Last validated (declared)", esc(feature.last_validated)]);
    return `<article class="feature">
      <div class="row"><span class="name">${esc(feature.title)}</span><code class="id">${esc(feature.id)}</code></div>
      <div class="row">${statusBadge(feature.status)} ${verdictBadge(v)}</div>
      ${v.warnings.map((w) => `<div class="warning">⚠ ${esc(w)}</div>`).join("")}
      <dl>${rows.map(([k, val]) => `<dt>${esc(k)}</dt><dd>${val}</dd>`).join("")}</dl>
    </article>`;
  }

  function featureGroups(features, open) {
    const groups = new Map();
    features.forEach((f) => {
      const key = `${areaTitle(f.area)} · ${f.category}`;
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push(f);
    });
    if (!groups.size) return '<p class="notice">No feature matches the search and filters.</p>';
    return [...groups.entries()].map(([title, items]) => {
      const counts = {};
      items.forEach((f) => { counts[f.status] = (counts[f.status] || 0) + 1; });
      return `<details class="group"${open ? " open" : ""}>
        <summary><span class="title">${esc(title)}</span><span class="muted">${items.length} feature${items.length > 1 ? "s" : ""}</span></summary>
        <div style="padding:0 14px 10px">${stackBar(counts, items.length)}${legend(counts)}</div>
        ${items.map(featureCard).join("")}
      </details>`;
    }).join("");
  }

  function indicatorCard(indicator) {
    const cls = indicator.id === "mzm" ? "mzm" : indicator.id === "aos" ? "aos" : indicator.id === "global" ? "global" : "";
    const features = data.features.filter((f) => indicator.features.includes(f.id) && matches(f));
    return `<div class="card ${cls}">
      <header><h3>${esc(indicator.title)}</h3><span class="muted">${indicator.total} registered</span></header>
      ${metric("Functional or better", indicator.functional_or_better_percent, indicator.functional_or_better, indicator.total, "working")}
      ${metric("With passing tests", indicator.with_passing_tests_percent, indicator.with_passing_tests, indicator.total, "tested")}
      ${stackBar(indicator.by_status, indicator.total)}${legend(indicator.by_status)}
      <details class="group" style="margin:10px 0 0"><summary><span class="title">Features</span><span class="muted">${features.length}</span></summary>
        ${features.map(featureCard).join("") || '<p class="feature muted">No match.</p>'}</details>
    </div>`;
  }

  function testsIndicator() {
    const t = data.tests;
    if (!t.summary) {
      return `<div class="card"><header><h3>Automated tests</h3></header>
        <p class="muted">Tests were not run when this data was generated (use <code>--run-tests</code>).
        ${t.ctest.length} CTest tests and ${t.python.length} Python modules are registered.</p></div>`;
    }
    const total = t.summary.passed + t.summary.failed + t.summary.other;
    const share = total ? Math.round((1000 * t.summary.passed) / total) / 10 : null;
    return `<div class="card"><header><h3>Automated tests</h3><span class="muted">on ${esc(t.host)}</span></header>
      <div class="big">${t.summary.passed}<span class="muted" style="font-size:1rem"> / ${total} passed</span></div>
      ${metric("Passing", share, t.summary.passed, total, "tested")}
      <p class="muted" style="margin:6px 0 0">${t.summary.failed} failed, ${t.summary.other} skipped or not run.
      ${t.ctest.length} CTest tests, ${t.python.length} Python modules.</p></div>`;
  }

  function inventoryPanel() {
    const inv = data.inventory;
    if (!inv || !inv.available) return "";
    const cards = ["mzm", "aos"].map((game) => {
      const g = inv.games[game];
      const unclassified = g.by_category.unclassified || 0;
      return `<div class="card ${game}"><header><h3>${esc(g.title)}</h3><span class="muted">native source inventory</span></header>
        <div class="big">${g.routines.toLocaleString("en")}<span class="muted" style="font-size:1rem"> routines discovered</span></div>
        <p class="muted" style="margin:8px 0 0">${(g.routines - unclassified).toLocaleString("en")} classified,
        ${unclassified.toLocaleString("en")} unclassified; ${g.routines_cited_by_features} cited as evidence by feature
        records; ${g.call_edges.toLocaleString("en")} call edges. Discovered is not ported: porting is tracked by the features above.</p></div>`;
    });
    return `<h2>Native source inventory</h2><div class="grid">${cards.join("")}</div>`;
  }

  function overview() {
    const indicators = data.indicators.map(indicatorCard).join("");
    return `<p class="notice">${esc(data.method)}</p>
      <h2>Indicators</h2><div class="grid">${indicators}${testsIndicator()}</div>
      ${inventoryPanel()}`;
  }

  function areaView(area) {
    const all = data.features.filter((f) => f.area === area);
    const indicator = data.indicators.find((i) => i.areas.length === 1 && i.areas[0] === area);
    const visible = all.filter(matches);
    return `<div class="grid">${indicator ? indicatorCard(indicator) : ""}</div>
      <h2>${esc(areaTitle(area))}</h2>${featureGroups(visible, true)}`;
  }

  function outcomeBadge(outcome) {
    if (outcome == null) return '<span class="badge warn">not run</span>';
    const tone = outcome === "passed" ? "ok" : outcome === "failed" ? "bad" : "warn";
    return `<span class="badge ${tone}">${esc(outcome)}</span>`;
  }

  function testsView() {
    const t = data.tests;
    const q = state.query;
    const ctest = t.ctest.filter((x) => !q || (x.name + " " + x.files.join(" ")).toLowerCase().includes(q));
    const python = t.python.filter((x) => !q || x.file.toLowerCase().includes(q));
    return `<div class="grid">${testsIndicator()}</div>
      <h2>CTest (${ctest.length})</h2>
      <div class="table-wrap"><table><thead><tr><th>Test</th><th>Sources</th><th>Result</th></tr></thead><tbody>
      ${ctest.map((x) => `<tr><td><code>${esc(x.name)}</code></td><td>${x.files.map((f) => `<code>${esc(f)}</code>`).join("<br>") || '<span class="muted">command</span>'}</td><td>${outcomeBadge(x.outcome)}</td></tr>`).join("")}
      </tbody></table></div>
      <h2>Python modules (${python.length})</h2>
      <div class="table-wrap"><table><thead><tr><th>Module</th><th>Tests</th><th>Result</th></tr></thead><tbody>
      ${python.map((x) => `<tr><td><code>${esc(x.file)}</code></td><td>${x.passed == null ? x.test_count : `${x.passed}/${x.test_count}`}</td><td>${outcomeBadge(x.outcome)}</td></tr>`).join("")}
      </tbody></table></div>`;
  }

  function timelineView() {
    const q = state.query;
    const entries = data.timeline.filter((e) => !q || (e.subject + " " + e.scope).toLowerCase().includes(q));
    return `<p class="notice">Commit history shows when work landed; it is not evidence that a feature works.</p>
      <ul class="timeline">${entries.map((e) => `<li class="scope-${esc(e.scope)}">
        <div class="date">${esc(e.date)} · <code>${esc(e.commit)}</code> · ${esc(e.scope)}</div>
        <div>${esc(e.subject)}</div></li>`).join("")}</ul>`;
  }

  function attentionView() {
    const flagged = data.features.filter((f) => matches(f) && (
      ["blocked", "unknown", "not_started", "in_progress", "partial"].includes(f.status) ||
      f.verification.warnings.length || ["failing", "missing_sources"].includes(f.verification.verdict)));
    const order = ["blocked", "unknown", "not_started", "in_progress", "partial", "functional", "faithful", "validated"];
    flagged.sort((a, b) => order.indexOf(a.status) - order.indexOf(b.status));
    const warnings = data.features.filter((f) => f.verification.warnings.length).length;
    return `<p class="notice">${flagged.length} features are blocked, unknown, unfinished or carry a verification warning
      (${warnings} with warnings).</p>${featureGroups(flagged, false)}`;
  }

  function render() {
    statusFilter.hidden = ["tests", "timeline"].includes(state.view);
    if (state.view === "overview") view.innerHTML = overview();
    else if (AREA_VIEWS.includes(state.view)) view.innerHTML = areaView(state.view);
    else if (state.view === "tests") view.innerHTML = testsView();
    else if (state.view === "timeline") view.innerHTML = timelineView();
    else view.innerHTML = attentionView();
  }

  function init() {
    if (!data || data.schema !== "metroidvania-dashboard-v1") {
      view.innerHTML = '<p class="notice">No dashboard data. Generate it with <code>python3 -m scripts.dashboard --run-tests</code>.</p>';
      toolbar.hidden = true;
      return;
    }
    const when = new Date(data.generated_at);
    document.getElementById("generated").innerHTML =
      `Generated ${esc(when.toLocaleString())}<br><code>${esc(data.git.branch)}@${esc(data.git.commit)}</code>${data.git.dirty ? " (uncommitted changes)" : ""}`;
    statusFilter.innerHTML = data.statuses.map((s) =>
      `<button class="chip" data-status="${esc(s.id)}" aria-pressed="false" title="${esc(s.description)}"><span class="dot" style="background:var(--s-${esc(s.id)})"></span>${esc(s.label)}</button>`).join("");
    statusFilter.addEventListener("click", (event) => {
      const chip = event.target.closest(".chip");
      if (!chip) return;
      const id = chip.dataset.status;
      if (state.statuses.has(id)) state.statuses.delete(id); else state.statuses.add(id);
      chip.setAttribute("aria-pressed", String(state.statuses.has(id)));
      render();
    });
    search.addEventListener("input", () => { state.query = search.value.trim().toLowerCase(); render(); });
    document.getElementById("tabs").addEventListener("click", (event) => {
      const button = event.target.closest("button[data-view]");
      if (!button) return;
      document.querySelectorAll("#tabs button").forEach((b) => b.classList.toggle("active", b === button));
      state.view = button.dataset.view;
      try { history.replaceState(null, "", `#${state.view}`); } catch (e) { /* file:// may refuse */ }
      render();
    });
    const initial = (location.hash || "").slice(1);
    const button = document.querySelector(`#tabs button[data-view="${CSS.escape(initial)}"]`);
    if (button) button.click(); else render();
  }

  init();
}());
