#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Validate parity annotations and generate the native parity checklist."""
from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "data/native_parity/inventory.json"
ANNOTATIONS = ROOT / "data/native_parity/annotations.json"
CHECKLIST = ROOT / "docs/NATIVE_PARITY_CHECKLIST.md"
INVENTORY_SCHEMA = "metroidvania-native-inventory-v1"
ANNOTATION_SCHEMA = "metroidvania-native-parity-annotations-v1"

CATEGORIES = (
    ("startup", "Startup and initialization"),
    ("title", "Title screen"),
    ("menus", "Menus and options"),
    ("input", "Controls and input"),
    ("interface", "HUD and interface"),
    ("player", "Player state machine"),
    ("physics", "Physics"),
    ("animation", "Animations"),
    ("collision", "Collisions, hitboxes and hurtboxes"),
    ("weapons", "Weapons and projectiles"),
    ("upgrades", "Upgrades and equipment"),
    ("abilities", "Powers and abilities"),
    ("enemies", "Enemies"),
    ("bosses", "Bosses"),
    ("items", "Items and drops"),
    ("environment", "Environment interactions"),
    ("rooms", "Rooms, areas and maps"),
    ("camera", "Camera and scrolling"),
    ("transitions", "Transitions"),
    ("events", "Events and scripts"),
    ("cutscenes", "Cutscenes"),
    ("audio", "Music and sound effects"),
    ("inventory", "Inventory and progression data"),
    ("progression", "Progression and unlock conditions"),
    ("saves", "Save and load"),
    ("death", "Death and game over"),
    ("victory", "Victory conditions"),
    ("endings", "Endings and credits"),
    ("technical", "GBA-specific technical systems"),
    ("data", "Native data definitions"),
    ("unclassified", "Unclassified source routines"),
)

STATUS_MARKS = {
    "missing": "[ ]",
    "partial": "[~]",
    "validated": "[x]",
    "research": "[?]",
    "blocked": "[!]",
}


def _load(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot load {path}: {exc}") from exc


def validate(inventory: dict, annotations: dict, root: Path = ROOT) -> list[str]:
    if inventory.get("schema") != INVENTORY_SCHEMA:
        raise ValueError("unsupported native inventory schema")
    if annotations.get("schema") != ANNOTATION_SCHEMA:
        raise ValueError("unsupported parity annotation schema")
    diagnostics = []
    category_ids = {item[0] for item in CATEGORIES}
    feature_ids = set()
    for game, game_annotations in annotations.get("games", {}).items():
        if game not in inventory.get("games", {}):
            raise ValueError(f"annotations reference unknown game: {game}")
        symbols = defaultdict(list)
        for routine in inventory["games"][game]["routines"]:
            symbols[routine["symbol"]].append(routine["id"])
        for feature in game_annotations.get("features", []):
            feature_id = feature.get("id", "")
            if not feature_id or feature_id in feature_ids:
                raise ValueError(f"missing or duplicate feature id: {feature_id!r}")
            feature_ids.add(feature_id)
            if feature.get("status") not in STATUS_MARKS:
                raise ValueError(f"{feature_id}: invalid status")
            if feature.get("category") not in category_ids:
                raise ValueError(f"{feature_id}: invalid category")
            for symbol in feature.get("native_symbols", []):
                matches = symbols.get(symbol, [])
                if not matches:
                    raise ValueError(f"{feature_id}: native symbol not found: {symbol}")
                if len(matches) > 1:
                    diagnostics.append(
                        f"{feature_id}: symbol {symbol} has {len(matches)} definitions")
            for field in ("local_sources", "tests"):
                for relative in feature.get(field, []):
                    if not (root / relative).is_file():
                        raise ValueError(f"{feature_id}: missing {field} path: {relative}")
            if feature.get("status") == "validated" and not feature.get("tests"):
                raise ValueError(f"{feature_id}: validated status requires tests")
    return diagnostics


def _link_paths(paths: list[str]) -> str:
    return ", ".join(f"[`{path}`](../{path})" for path in paths) or "none recorded"


def _symbol_ids(game_data: dict, symbols: list[str]) -> list[str]:
    wanted = set(symbols)
    return [routine["id"] for routine in game_data["routines"]
            if routine["symbol"] in wanted]


def render(inventory: dict, annotations: dict) -> str:
    lines = [
        "# Native parity checklist",
        "",
        "This file is generated by `python3 -m scripts.rebuild --checklist` from",
        "the automatic source inventory and the separate human annotations in",
        "`data/native_parity/`. Do not edit it directly.",
        "",
        "> Scope warning: this is the first static inventory pass. It indexes C",
        "> definitions, exported assembly functions and resolved direct lexical",
        "> calls. Header-only declarations, indirect calls, data tables and runtime",
        "> observations are not indexed yet. Counts are discovery coverage, not game",
        "> fidelity percentages.",
        "",
        "## Status legend",
        "",
        "- `[ ]` not implemented",
        "- `[~]` partially implemented",
        "- `[x]` implemented and behaviorally validated",
        "- `[?]` research or identification required",
        "- `[!]` blocked or known problem",
        "",
        "## Automatic inventory summary",
        "",
        "| Game | Source revision | Routines | Addressed | Static call edges | Annotated features |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for game in ("mzm", "aos"):
        game_data = inventory["games"][game]
        stats = game_data["statistics"]
        feature_count = len(annotations["games"][game]["features"])
        lines.append(
            f"| {game_data['title']} | `{game_data['source_revision'][:12]}` | "
            f"{stats['routines']} | {stats['with_source_address']} | "
            f"{stats['resolved_call_edges']} | {feature_count} |")
    lines.extend([
        "",
        "The complete machine-readable records, stable routine IDs and caller/callee",
        "edges are in [`data/native_parity/inventory.json`](../data/native_parity/inventory.json).",
        "",
    ])

    for game in ("mzm", "aos"):
        game_data = inventory["games"][game]
        game_annotations = annotations["games"][game]
        features_by_category = defaultdict(list)
        for feature in game_annotations["features"]:
            features_by_category[feature["category"]].append(feature)
        category_counts = game_data["statistics"]["by_category"]
        lines.extend([
            f"## {game_data['title']}",
            "",
            f"Pinned source: `{game_data['source_root']}` at "
            f"`{game_data['source_revision']}`.",
            "",
        ])
        for category, title in CATEGORIES:
            count = category_counts.get(category, 0)
            features = sorted(features_by_category.get(category, []),
                              key=lambda item: item["id"])
            if not features and count == 0 and category in {"data", "unclassified"}:
                continue
            lines.extend([
                f"### {title}",
                "",
                f"[?] **`{game}.{category}.inventory-boundary` — source coverage.** "
                f"The current classifier assigns {count} discovered routine(s) to "
                "this category. Category completeness has not been established.",
                "",
            ])
            for feature in features:
                symbol_ids = _symbol_ids(game_data, feature.get("native_symbols", []))
                lines.append(
                    f"{STATUS_MARKS[feature['status']]} **`{feature['id']}` — "
                    f"{feature['title']}.** {feature['notes']}")
                lines.append("")
                lines.append(
                    f"Native evidence: {', '.join(f'`{item}`' for item in symbol_ids) or 'not attached yet'}.  ")
                lines.append(f"Local implementation: {_link_paths(feature.get('local_sources', []))}.  ")
                lines.append(f"Tests: {_link_paths(feature.get('tests', []))}.")
                lines.append("")

        missing = game_data["coverage"]["not_yet_indexed"]
        lines.extend([
            "### Known inventory gaps",
            "",
        ])
        lines.extend(f"- [!] {item}." for item in missing)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_checklist(text: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(output)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--inventory", type=Path, default=INVENTORY)
    parser.add_argument("--annotations", type=Path, default=ANNOTATIONS)
    parser.add_argument("--output", type=Path, default=CHECKLIST)
    parser.add_argument("--check", action="store_true",
                        help="fail when the generated checklist differs")
    args = parser.parse_args(argv)
    try:
        inventory = _load(args.inventory)
        annotations = _load(args.annotations)
        diagnostics = validate(inventory, annotations, args.root.resolve())
        generated = render(inventory, annotations)
        if args.check:
            existing = args.output.read_text(encoding="utf-8")
            if existing != generated:
                raise ValueError(f"generated checklist is stale: {args.output}")
        else:
            write_checklist(generated, args.output)
    except ValueError as exc:
        parser.error(str(exc))
    for diagnostic in diagnostics:
        print(f"warning: {diagnostic}")
    print(f"Checklist {'checked' if args.check else 'written'}: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
